### ISSUE TITLE
Help and feedback

### ISSUE THREAD

**Issue by FranW1** [hmcts/design-system-backlog#31]
We are working on a common pattern for capturing user help and feedback within services.

<img width="555" alt="screen shot 2018-08-01 at 13 58 13" src="https://user-images.githubusercontent.com/30631036/43523052-10aa311a-9593-11e8-80e5-d74f6f7a55cb.png">

**Comment by blowfishsoup** [comment]
Could/should we include an instant messaging option in there too?

**Comment by PamelaWoods** [comment]
@PeteWilliams - Art was writing stories with Denise a few weeks ago to get the Help & Feedback module built.  Can we get the frontend designs into the pattern library please as a PATTERN.

**Comment by DeniseHampson** [comment]
Here is a link to the latest prototype for the help and feedback pages. And the designs are shown below.

https://reformhelp.herokuapp.com/start
user: reform
pass: help

**Comment by DeniseHampson** [comment]
![help web forms-11](https://user-images.githubusercontent.com/41999075/46077884-50337f80-c18a-11e8-8b69-7a27ee0eb194.jpg)

![help web forms v2-11](https://user-images.githubusercontent.com/41999075/46734168-59444680-cc8a-11e8-9dba-89d1538f06e3.jpg)

![help web forms-13](https://user-images.githubusercontent.com/41999075/46077898-5de90500-c18a-11e8-899b-8a709493d012.jpg)

**Comment by PamelaWoods** [comment]
Add this to PATTERNS.
Create a gif to show the flow.
Use the latest designs.

**Comment by DeniseHampson** [comment]
**When to use this component**
Use this component at the bottom of every page of your service.

Some services, for example the SSCS ‘Submit Your Appeal’, have to be completed in one session. These users will need more instant support, in which case the web form may not be the most appropriate. Instead, just a phone number will suffice here (or web chat if it becomes available). Each service will need to determine the best combination of help channels they offer to users. They will also need to determine the response time. E.g. the pattern shows 10 working days for CMC. Each service will be different.


**When not to use this component**
As mentioned above, each service will need to determine the best combination of help channels they offer to users.


**How it works**
When a user needs help they can choose between making a call and completing an online form. The contents of the online form, along with additional data, such as the page url, date, time etc. are routed through to a customer service agent who can triage the issue and respond quickly to the user if required.


**What you need to do first**
Implementing this pattern requires an agreement of where the issue will be routed, who will read it, respond to it, and the time frame within which they will respond.

**Comment by PamelaWoods** [comment]
@DeniseHampson - could you please add the original design showing Email (webforms), Webchat and Telelphone?  These options should then be configurable by a service to be turned on or off as required.  The latest prototype and designs on this ticket do not show Webchat.

**Comment by blowfishsoup** [comment]
<img width="1535" alt="screenshot 2018-11-15 at 09 29 16" src="https://user-images.githubusercontent.com/6122620/48543242-0842f600-e8b9-11e8-8783-6b38186603d6.png">


@FranW1  @DeniseHampson This is what we have so far for VH but happy to amend if there are different patterns available. We'll be testing with users on Wed 21 Nov.

**Comment by DeniseHampson** [comment]
@FranW1 @blowfishsoup Hi, thanks. It will be so valuable to learn more about users' expectations for the different help channels available on VH.

One thing... the pattern says 'Contact us for help' rather than 'Contact us if you need help'. Small tweak I know, but we need consistency.

Also, do you think it would look better if a little extra vertical space is added between the 'Continue' button and the 'Contact us for help' link? With the link expanded there's a lot of text going on in a small space with the green action button in the middle. What do you think?

And tighten the space between the 'Telephone', 'Email' titles and the details under each one?

I'm being detailed here. But it looks great and I'll be very interested in the outcomes.

**Comment by adamsilver** [comment]
Also the left border for the [Details](https://design-system.service.gov.uk/components/details/) component is missing. That helps to group what has been expanded to the thing that the user clicked.

**Comment by blowfishsoup** [comment]
@DeniseHampson @adamsilver Apologies - my fault about the border and the proper text - will sort those out now. I will also play with the spacing - I agree there needs to be more vertical space beneath the green button. Thanks for the feedback :-)

**Comment by DeniseHampson** [comment]
Yes the left border! I knew there was something else missing. Good spot @adamsilver . I need to play more spot the difference :)

**Comment by blowfishsoup** [comment]
<img width="1535" alt="screenshot 2018-11-15 at 10 22 37" src="https://user-images.githubusercontent.com/6122620/48546488-68896600-e8c0-11e8-96d8-eaa7e376e893.png">
@DeniseHampson @adamsilver Updated version

**Comment by adamsilver** [comment]
I've added the guidance and the video here:
http://hmcts-design-system.herokuapp.com/patterns/get-support-online

I'm sure we'll still need to update bits of this. But it's a start.

**Comment by PeteWilliams** [comment]
We've added this to CMC. It appears at the bottom of every page, eg: https://hmcts-cmc-prototype.herokuapp.com/prototypes/features-to-be-built/dashboard/claimant-response/admit-the-claim/task-list/check-and-send (U: cmc p: cmc_summer)

We've not tested it yet, but some very minor points that we noticed when implementing it…

* I'd say you're better off making the form fields appropriate sizes rather than all full width - makes them more indicative of their contents at a glance. Would match the rest of our service at least.
* It says 'email' as a header, but then goes to a contact form rather than showing an email address. Slightly different things.
* The headers followed by the links are a bit repetitive, I wonder if we could just make the links bigger so they act as headers and ditch the H2s?
* On the [feedback page](https://hmcts-cmc-prototype.herokuapp.com/prototypes/prototype-oct-2018/misc/feedback), we have the contact expander at the bottom (by virtue of it being on every page), but also a 'contact us' link in the second line. However the link just takes them to the 'send a message' page - they can't find phone number etc here, when they may well need it. Maybe replace this link with one that expands with the full details and ditch the one at the bottom?
* I notice live chat has been added since we added this - should probably be a lowercase C?

**Comment by adamsilver** [comment]
Could we add a label, in the same style as “Your email address” and “Your telephone number” above the big text box at the top?

**Comment by PeteWilliams** [comment]
Quick mockup of the sort of thing I meant with regards to the H2s/links to avoid duplication:

![image](https://user-images.githubusercontent.com/1325606/49156100-71445800-f314-11e8-8f1e-64f3ce544348.png)

**Comment by adamsilver** [comment]
I like that it's more concise, I just worry that it's harder to spot links this way when part of the h2s/h3s.

**Comment by DeniseHampson** [comment]
This is what the design would look like following last week's discussion...
![image](https://user-images.githubusercontent.com/41999075/49510018-fa144400-f87e-11e8-94d5-3557cc5ffeb2.png)
![image](https://user-images.githubusercontent.com/41999075/49510044-07313300-f87f-11e8-9573-de8feb604453.png)

**Comment by adamsilver** [comment]
Now in the design system. Here's the latest prototype:
https://contact-us-prototype.herokuapp.com/
